In [1]:
print("hello world")

hello world


In [11]:
import numpy as np

game_space = np.array([[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]])
print("Initial state:\n", game_space)

Initial state:
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [12]:
import random

i = 0

while np.isnan(game_space).any():
    # get nan elements' indices
    nan_elements_idx = np.argwhere(np.isnan(game_space)) 
    print(nan_elements_idx)

    computer_step = random.randint(0, len(nan_elements_idx)-1)
    print(computer_step)

    game_space[tuple(nan_elements_idx[computer_step])] = 1
    print(game_space)


[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]
7
[[nan nan nan]
 [nan nan nan]
 [nan  1. nan]]
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 2]]
7
[[nan nan nan]
 [nan nan nan]
 [nan  1.  1.]]
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]]
6
[[nan nan nan]
 [nan nan nan]
 [ 1.  1.  1.]]
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]
0
[[ 1. nan nan]
 [nan nan nan]
 [ 1.  1.  1.]]
[[0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]
4
[[ 1. nan nan]
 [nan nan  1.]
 [ 1.  1.  1.]]
[[0 1]
 [0 2]
 [1 0]
 [1 1]]
0
[[ 1.  1. nan]
 [nan nan  1.]
 [ 1.  1.  1.]]
[[0 2]
 [1 0]
 [1 1]]
0
[[ 1.  1.  1.]
 [nan nan  1.]
 [ 1.  1.  1.]]
[[1 0]
 [1 1]]
0
[[ 1.  1.  1.]
 [ 1. nan  1.]
 [ 1.  1.  1.]]
[[1 1]]
0
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
game_space[tuple(nan_elements_idx[computer_step])]

np.float64(nan)

In [21]:
tuple(nan_elements_idx[computer_step])

(np.int64(1), np.int64(0))

In [1]:
x = ("1", "2")

In [5]:
x_int = tuple((int(element) for element in x))

In [6]:
x_int

(1, 2)

In [4]:
x

('1', '2')

In [2]:
game_space[0][1] = 1
game_space

array([[nan,  1., nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [7]:
x = "12"
x[0]

'1'

tuple("12")

In [16]:
if np.isnan(game_space[0][1]):
    print("bruh")
else:
    print("shii")

bruh


In [3]:

game_space[0][1] 

np.float64(1.0)

In [4]:
for x in np.nditer(game_space):
    print(x)

nan
1.0
nan
nan
nan
nan
nan
nan
nan


In [5]:
for i in range(0,3):
    print(i)

0
1
2


In [9]:
game_space[0][1] = "o"

ValueError: could not convert string to float: 'o'

In [8]:
type(game_space[0][1])

numpy.float64

In [10]:
np.float64(1)

np.float64(1.0)