In [1]:
print("hello world")

hello world


In [8]:
import numpy as np

game_space = np.array([[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]])
print("Initial state:\n", game_space)

Initial state:
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [9]:
import random

i = 0

#while np.isnan(game_space).any():
    # get nan elements' indices
nan_elements_idx = np.argwhere(np.isnan(game_space)) 
print(nan_elements_idx)

computer_step = random.randint(0, len(nan_elements_idx))

game_space[nan_elements_idx[computer_step]] = 1
print(f"Iteration {i}", game_space)

i = i + 1

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]
Iteration 0 [[nan nan nan]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[0 0]
 [0 1]
 [0 2]]


KeyboardInterrupt: 

In [7]:
game_space[[1, 2]]

array([[1., 1., 1.],
       [1., 1., 1.]])