In [1]:
print("hello world")

hello world


In [23]:
import numpy as np

game_space = np.array([[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]])
print("Initial state:\n", game_space)

Initial state:
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [25]:
import random

i = 0

while np.isnan(game_space).any():
    # get nan elements' indices
    nan_elements_idx = np.argwhere(np.isnan(game_space)) 
    print(nan_elements_idx)

    computer_step = random.randint(0, len(nan_elements_idx)-1)
    print(computer_step)

    game_space[tuple(nan_elements_idx[computer_step])] = 1
    print(game_space)


[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]]
5
[[nan nan nan]
 [nan nan  1.]
 [nan nan  1.]]
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [2 0]
 [2 1]]
3
[[nan nan nan]
 [ 1. nan  1.]
 [nan nan  1.]]
[[0 0]
 [0 1]
 [0 2]
 [1 1]
 [2 0]
 [2 1]]
5
[[nan nan nan]
 [ 1. nan  1.]
 [nan  1.  1.]]
[[0 0]
 [0 1]
 [0 2]
 [1 1]
 [2 0]]
4
[[nan nan nan]
 [ 1. nan  1.]
 [ 1.  1.  1.]]
[[0 0]
 [0 1]
 [0 2]
 [1 1]]
1
[[nan  1. nan]
 [ 1. nan  1.]
 [ 1.  1.  1.]]
[[0 0]
 [0 2]
 [1 1]]
0
[[ 1.  1. nan]
 [ 1. nan  1.]
 [ 1.  1.  1.]]
[[0 2]
 [1 1]]
1
[[ 1.  1. nan]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[0 2]]
0
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
game_space[tuple(nan_elements_idx[computer_step])]

np.float64(nan)

In [21]:
tuple(nan_elements_idx[computer_step])

(np.int64(1), np.int64(0))

In [1]:
x = ("1", "2")

In [5]:
x_int = tuple((int(element) for element in x))

In [6]:
x_int

(1, 2)

In [4]:
x

('1', '2')